import type { Metadata } from "next";
import MuiDrawer from "@/components/MuiDrawer";
import { Box } from "@mui/material";
import "@/css/layout.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box sx={{ display: "flex", flexDirection: "row" }}>
      <MuiDrawer></MuiDrawer>
      <Box sx={{ display: "flex", justifyContent: "center", width: "100%" }}>
        {children}
      </Box>
    </Box>
  );
}
